inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

# ref)
# https://raw.githubusercontent.com/onk/onkcop/master/config/rubocop.yml

# 自動生成されるものはチェック対象から除外する
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - "vendor/**/*"
    - "bin/*"
    - "Gemfile*"
    - "db/schema.rb"
    - "db/seeds.rb"
