postgresql:
  adapter: postgresql
  host: <%= ENV.fetch('POSTGRESQL_HOST', '127.0.0.1') %>
  database: cursor_test
  username: postgres
  password:
mysql:
  adapter: mysql2
  host: <%= ENV.fetch('MYSQL_HOST', '127.0.0.1') %>
  database: cursor_test
  username: root
  password:
