postgresql:
  adapter: postgresql
  host: localhost
  database: cursor_test
  username: postgres
  password:
mysql:
  adapter: mysql2
  host: localhost
  database: cursor_test
  username: root
  password:
